# Generated by Django 5.1.1 on 2024-09-26 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_type',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('borrower', 'Borrower'), ('investor', 'Investor'), ('staff', 'Staff')], default='borrower', max_length=10),
        ),
    ]
