# Generated by Django 5.1.1 on 2024-10-01 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_checklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='identity_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
