# Generated by Django 5.1.1 on 2024-10-02 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_first_name_alter_user_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbankdetails',
            name='account_numberaccount_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
