# Generated by Django 5.1.1 on 2024-10-02 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_userbankdetails_account_numberaccount_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbankdetails',
            name='account_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
