# Generated by Django 5.1.1 on 2024-10-02 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_userbankdetails_account_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbankdetails',
            old_name='account_numberaccount_type',
            new_name='account_type',
        ),
    ]
