# Generated by Django 5.1.1 on 2025-11-17 19:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_passwordresettoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('fund_added', 'Fund Added'), ('fund_withdrawn', 'Fund Withdrawn'), ('investment_made', 'Investment Made'), ('investment_return', 'Investment Return'), ('loan_funded', 'Loan Funded'), ('loan_fulfilled', 'Loan Fulfilled'), ('loan_approved', 'Loan Approved')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_id', models.IntegerField(blank=True, help_text='ID of related object (loan, investment, etc.)', null=True)),
                ('related_type', models.CharField(blank=True, help_text='Type of related object', max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read', '-created_at'], name='notificatio_user_id_c4e471_idx')],
            },
        ),
    ]
