# Generated by Django 5.1.1 on 2024-10-06 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investorbalance',
            old_name='investor',
            new_name='user',
        ),
    ]
