# Generated by Django 5.1.1 on 2024-10-07 04:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditScoreHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_score', models.IntegerField()),
                ('average_transaction', models.IntegerField()),
                ('credit_utilization', models.IntegerField()),
                ('payment_consistency', models.IntegerField(blank=True)),
                ('date_recorded', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'credit_score_history',
            },
        ),
        migrations.CreateModel(
            name='Borrower',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('bank_statement_url', models.CharField(max_length=255)),
                ('loan_purpose', models.CharField(max_length=255)),
                ('employment_status', models.CharField(choices=[('employed', 'Employed'), ('self-employed', 'Self-Employed'), ('unemployed', 'Unemployed'), ('student', 'Student')], max_length=20)),
                ('annual_income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('account_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('credit_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='borrower.creditscorehistory')),
            ],
            options={
                'db_table': 'Borrower',
            },
        ),
    ]
