# Generated by Django 5.1.1 on 2024-10-07 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrower', '0003_creditscorehistory_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditscorehistory',
            name='statement_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creditscorehistory',
            name='statement_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
