# Generated by Django 5.1.1 on 2024-10-07 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrower', '0004_creditscorehistory_statement_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditscorehistory',
            name='average_transaction',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='creditscorehistory',
            name='credit_utilization',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='creditscorehistory',
            name='payment_consistency',
            field=models.FloatField(blank=True),
        ),
    ]
