# Generated by Django 5.1.1 on 2024-10-08 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borrower', '0005_alter_creditscorehistory_average_transaction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrower',
            name='bank_statement_url',
        ),
        migrations.RemoveField(
            model_name='borrower',
            name='credit',
        ),
        migrations.RemoveField(
            model_name='borrower',
            name='loan_purpose',
        ),
    ]
