# Generated by Django 5.1.1 on 2024-10-08 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrower', '0006_remove_borrower_bank_statement_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditscorehistory',
            name='user',
        ),
        migrations.AddField(
            model_name='creditscorehistory',
            name='borrower',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='borrower.borrower'),
        ),
    ]
