# Generated by Django 5.1.1 on 2024-10-16 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='loan_purpose',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
