# Generated by Django 5.1.1 on 2024-10-16 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_loan_loan_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('approved', 'Approved'), ('repaid', 'Repaid'), ('defaulted', 'Defaulted')], max_length=20),
        ),
    ]
