# Generated by Django 5.1.1 on 2024-10-16 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_alter_loan_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanrepaymentschedule',
            name='due_date',
            field=models.DateTimeField(null=True),
        ),
    ]
