# Generated by Django 5.1.1 on 2024-10-16 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_alter_loanrepaymentschedule_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='is_fulfill',
            field=models.BooleanField(default=False),
        ),
    ]
