# Generated by Django 5.1.1 on 2024-10-16 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0005_loan_is_fulfill'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='net_return',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
