# Generated by Django 5.1.1 on 2024-10-16 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0006_investment_net_return'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investment',
            name='net_return',
        ),
    ]
