# Generated by Django 5.1.1 on 2024-10-18 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0007_remove_investment_net_return'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='net_return',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
