# Generated by Django 5.1.1 on 2024-10-20 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0009_investment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='closed_at',
            field=models.DateTimeField(null=True),
        ),
    ]
