# Generated by Django 5.1.1 on 2024-10-20 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0010_investment_closed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrepaymentschedule',
            name='last_missed_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
